import type { Metadata } from "next";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { AppConvexProvider } from "@/components/providers/convex-provider";
import { MedialistAuthProvider } from "@/components/providers/medialist-auth-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "flex min-h-svh flex-col antialiased",
        )}
        suppressHydrationWarning
      >
        <AppConvexProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <MedialistAuthProvider>
              <Navbar />
              {children}
              <Footer />
            </MedialistAuthProvider>
          </ThemeProvider>
        </AppConvexProvider>
      </body>
    </html>
  );
}
